### ISSUE TITLE
Verwirrendes / Schlecht erkennbares Textlayout

### ISSUE THREAD

**Issue by FrederikWolter** [Robin2800/central-campus-management-portal#20]
Auf der [Subsite](https://robin2800.github.io/central-campus-management-portal/Impressum/impressum.html), finde ich, ist der Textfluss nicht gut erkennbar. Die Columns sind aufgrund des Hintergrunds nicht gut zu erkennen: @Hassoneh 

![Screenshot 2021-05-31 155110](https://user-images.githubusercontent.com/35914049/120203486-1020d680-c228-11eb-8d97-bcc484c50012.png)

LG Frederik

**Comment by Robin2800** [comment]
Danke fürs Feedback @FrederikWolter 👍🏽 

@Hassoneh kannst du dir das mal ansehen und dich dann darum kümmern, danke.
