### ISSUE TITLE
Mit ultra-wide Monitor wird das Hintergrund-Bild nicht richtig angezeigt

### ISSUE THREAD

**Issue by FrederikWolter** [Robin2800/central-campus-management-portal#4]
Mit ultra-wide Monitor wird das Hintergrund-Bild nicht richtig angezeigt:
![grafik](https://user-images.githubusercontent.com/35914049/116557818-1d803380-a8ff-11eb-9305-32249a787246.png)

Das ist potentiell wichtig, da Martin auch einen ultra-wide Monitor hat.

**Comment by Robin2800** [comment]
Aha, danke dir für die Info! Hätte es erstmal so direkt nicht bemerkt. Dann wäre es schon wichtig das zu ändern. 😄

**Comment by Robin2800** [comment]
Hab es angepasst bced87e5c1ec3071722d96a6d76387e35c4f522a

**Comment by Robin2800** [comment]
Hab es nun angepasst.
Siehe bced87e5c1ec3071722d96a6d76387e35c4f522a
